name: environment_config
description: Environment specific config generator. Allows to specify env configuration during CI/CD build. Primarily created to simplify Flutter build configuration
version: 1.1.1
author: TatsuUkraine <tatsu.ukraine@gmail.com>
homepage: https://github.com/TatsuUkraine/dart_environment_config
repository: https://github.com/TatsuUkraine/dart_environment_config
issue_tracker: https://github.com/TatsuUkraine/dart_environment_config/issues

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  dart_style: ^1.3.3
  code_builder: ^3.2.1
  args: ^1.5.2
  yaml: ^2.2.0

# Config example. Run `flutter pub run environment_config:generate --env=YOUR_VALUE` to see example
environment_config:
  fields:
    env: